api:
  name:    "gbe-salesforce-proxy-oauth" #${project.artifactId} # replaced through Maven resource filtering
  version: "v1" #${project.version}    # replaced through Maven resource filtering
  id: "16911805"
http:      
  listener:
    host: "0.0.0.0"
    port: "8091"    
    version: "/*"
  successcode: "200"
  failurecode: "500"     
  requester:
    username: "637fcf6f13514c2fbc3e946cca8d2063"      
  premise:
    mule4migrate: "false"      
    timeout: "3000000"
    connectionidletime: "120000"
    responsetime: "120000"
    port: "8091"
    mule4port: "8091"
    mule4host:  "mule-worker-internal-premiseassets-papi-dev01.us-e1.cloudhub.io"
    host: "mule-worker-internal-apidev-premiseassets-fr.cloudhub.io"
    reconnection:
      attempts: "2"      
  serviceOrders:
    mule4migrate: "false"     
    timeout: "3000000"
    connectionidletime: "120000"
    responsetime: "120000"
    port: "8091"
    mule4port: "8093"
    mule4host:  "mule-worker-internal-serviceorders-papi-dev01.us-e1.cloudhub.io"
    host: "mule-worker-internal-apidev-serviceorders-fr.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"    
      attempts: "2"      
  workOrders:
    mule4migrate: "false"    
    timeout: "3000000"
    connectionidletime: "120000"
    responsetime: "120000"
    port: "8091"
    mule4port: "8091"
    mule4host:  "mule-worker-internal-workorders-gbe-papi-dev01.us-e1.cloudhub.io"
    host: "mule-worker-internal-apidev-workorders-fr.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"      
  customer:
    mule4migrate: "false"    
    timeout: "3000000"
    connectionidletime: "120000"
    responsetime: "120000"
    port: "8091"
    mule4port: "8091"
    mule4host:  "mule-worker-internal-customers-papi-dev01.us-e1.cloudhub.io"
    host: "mule-worker-internal-apidev-ngcustomers-fr.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
  preferences:
    mule4migrate: "false"
    host: "testsecure-api.nationalgridus.com"    
    timeout: "3000000"
    connectionidletime: "120000"
    responsetime: "120000"
    port: "443"
    protocol: "HTTPS"
    baseuri: "/xapi/preferences"
    apiName:  "preference-gbe-eapi"
    tls:
      cert:
        path: "keystore/qa-mtls-sfpmapi.nationalgridus.com.pfx"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
    migrate:
      host: "api-uat-us01.nationalgrid.com"      
      port: "443"
      protocol: "HTTPS"
      apiName:  "preference-gbe-eapi"
  contacts:
    mule4migrate: "false"  
    timeout: "3000000"
    connectionidletime: "120000"
    responsetime: "120000"
    port: "443"
    host: "dev-api.nationalgridus.com"
    protocol: "HTTPS"
    baseuri: "/ng-contactpref-exp"
    apiName:  "contact-sc-eapi"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
    migrate:
      host: "api-uat-us01.nationalgrid.com"      
      port: "443"
      protocol: "HTTPS"
      apiName:  "contact-sc-eapi"
  commons:    
    timeout: "3000000"
    connectionidletime: "120000"
    responsetime: "120000"
    port: "8091"
    mule4migrate: "false" 
    mule4port: "8093"
    mule4host:  "mule-worker-internal-serviceorders-papi-dev01.us-e1.cloudhub.io"
    host: "mule-worker-internal-apidev-ng-common-fr.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"     
##cris customer    
  crisCustomer:
    host: "api-qa-us01.nationalgrid.com"
    port: "443"
    basepath: "proxy-dev-cris-customer"
    version: "v01"
    requestpath: "/crisCustomer"
    timeout: "3000000"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"   
  updatecustomer:
    host: "api-dev-int-us.nationalgrid.com"
    port: "443"
    basepath: "cris-customer-proxy-dev01"
    version: "v01"
    requestpath: "/phoneCustomer"
    timeout: "3000000"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
##M-TLS configurations
salesforce:
    mtls: 
      validation:
        enabled: "N"
tls.keystore:
  type: "pkcs12"
  path: "certs/ng-dev.p12"
  alias: "server"   

json.logger:
  prettyPrint: "true"
  disabled.fields: ""
##Alert Notification CloudHub Connector Properties##
ch:
  username: "NGLocalUser"

domain: "gbe-salesforce-proxy-oauth-dev01"
environment.id: "3cb0e531-c1a2-420a-8322-6fc16f3a6a81"
