api:
  name:    "gbe-salesforce-proxy-oauth" #${project.artifactId} # replaced through Maven resource filtering
  version: "v1" #${project.version}    # replaced through Maven resource filtering
  id: "16660772"
http:
  private:
    port: "8091"    
  listener:
    host: ""
    port: "8091"
    basepath: "proxyapi"
    version: "/*"
    config: HTTPS_Shared_Listener_Config
  requester:
    username: "637fcf6f13514c2fbc3e946cca8d2063" 
    
  premise:
    basepath: ""
    version: "v1"
    requestpath: "/premise"
    timeout: "3000000"
    port: "8093"
    host: "mule-worker-internal-apidev-premiseassets.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
      
  assets:
    basepath: ""
    version: "v1"
    requestpath: "/assets"
    timeout: "3000000"
    port: "8093"
    host: "mule-worker-internal-apidev-premiseassets-fr.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
      
  serviceOrders:
    basepath: ""
    version: "v04"
    requestpath: "/serviceOrders"
    timeout: "3000000"
    port: "8093"
    host: "mule-worker-internal-apidev-serviceorders.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
      
  workOrders:
    basepath: ""
    version: "v1"
    requestpath: "/workOrders"
    timeout: "3000000"
    port: "8093"
    host: "mule-worker-internal-apidev-workorders-v02.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
      
  customer:
    basepath: ""
    version: "v1"
    requestpath: "/customer"
    timeout: "3000000"
    port: "8093"
    host: "mule-worker-internal-apidev-customers.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
## dummy common and preferences contacts     
  commons:    
    timeout: "3000000"
    port: "8091"
    host: "mule-worker-internal-apidev-ng-common-fr.cloudhub.io"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
  preferences:
    host: "testsecure-api.nationalgridus.com"    
    timeout: "3000000"
    port: "443"
    protocol: "HTTPS"
    baseuri:  "/xapi/preferences"
    client_id:  ""
    tls:
      cert:
        path: "keystore/qa-mtls-sfpmapi.nationalgridus.com.pfx"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
  contacts:    
    timeout: "3000000"
    port: "8091"
    host: "dev-api.nationalgridus.com"
    protocol: "HTTPS"
    baseuri:  "/ng-contactpref-exp"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
##cris customer      
  crisCustomer:
    host: "localhost"
    port: "8086"
    basepath: "cris-customer-proxy"
    version: "v01"
    requestpath: "/crisCustomer"
    timeout: "3000000"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
      
  updatecustomer:
    host: "localhost"
    port: "8086"
    basepath: "cris-customer-proxy"
    version: "v01"
    requestpath: "/phoneCustomer"
    timeout: "3000000"
    reconnection:
      attempts: "2"
      frequency: "30000"
    untilsuccessful:
      frequency: "30000"
      attempts: "2"
##M-TLS configurations
salesforce:
    mtls: 
      validation:
        enabled: "N"
tls.keystore:
  type: "pkcs12"
  path: "certs/ng-dev.p12"
  alias: "server" 

json.logger:
  prettyPrint: "true"
  disabled.fields: ""    
ch:
  username: "NGLocalUser"

domain: "gbe-salesforce-proxy-oauth-local"
environment.id: "3cb0e531-c1a2-420a-8322-6fc16f3a6a81"

